services:
  cs_server:
    build: .
    ports:
      - "27016:27015/udp"
    command: /steam/start.sh
    develop:
      watch:
        - action: rebuild
          path: ./amxmodx/configs/
          target: /dedicated_server/cstrike/addons/amxmodx/configs
          ignore:
            - "**/*.Identifier"
            - "**/*.log"
        - action: rebuild
          path: ./amxmodx/scripting/
          target: /custom_scripting
          ignore:
            - "**/*.Identifier"
      
volumes:
  cs_server_data: