services:
  cs_server:
    build: .
    ports:
      - "27016:27015/udp"
    command: /steam/start.sh
    develop:
      watch:
        - action: rebuild
          path: ./amxmodx/configs/
          target: /dedicated_server/cstrike/addons/amxmodx/configs
      
volumes:
  cs_server_data: